project:
  title: "paulrjohnson.net"
  execute-dir: project

format: 
  hugo:
    fig-width: 12
    fig-height: 8
    fig-align: center
    warning: false

editor_options: 
  chunk_output_type: console
