project:
  type: website
  resources: _redirects

website:
  title: Paul Johnson
  site-url: https://paulrjohnson.net
  description: A Data Scientist Using Causal Inference & Machine Learning to Confirm His Priors.
  favicon: assets/img/favicon/favicon.ico
  search: false
  page-navigation: true
  back-to-top-navigation: false
  twitter-card: true
  open-graph: true
  image: assets/img/paul/paul.webp
  image-alt: Me looking handsome as hell
  comments: false

  navbar:
    title: P(Johnson) > 0.05
    logo: assets/img/favicon/favicon.ico
    logo-alt: Purple Octopus
    tools:
      - icon: github
        aria-label: GitHub
        href: https://www.github.com/paulj1989/paulrjohnson.net
      - icon: cup-hot-fill
        aria-label: Buy Me a Coffee
        href: https://www.buymeacoffee.com/paulj1989
    right:
      - text: Blog
        aria-label: Blog
        href: blog/index.qmd
      - text: Projects
        aria-label: Project Portfolio
        href: projects/index.qmd
      - text: Consultancy
        aria-label: Consultancy Enquiries
        href: consultancy/index.qmd
      - text: Curriculum Vitae
        aria-label: Curriculum Vitae
        href: cv/index.qmd

  page-footer:
    left: 2024 Paul Johnson &#8729; Made with [Quarto](https://quarto.org)

    right:
      - text: Contact
        aria-label: Contact Form
        href: contact.qmd
      - text: License
        aria-label: License Details
        href: license.qmd

format:
  html:
    theme:
      - cosmo
      - assets/css/theme.scss
    highlight-style: assets/github-plus.theme
    # pagetitle: "{{< meta title >}} | Paul Johnson"
    fig-align: center
    lightbox: true
    mermaid:
      theme: neutral

knitr:
  opts_chunk:
    dev: ragg_png

execute:
  freeze: auto
  warning: false
  error: false

include-in-header:
  - assets/umami.html
