project:
  type: website
  resources: _redirects
  pre-render: build/redirects.lua
  post-render: bash build/purge_css.sh

website:
  title: Paul Johnson
  site-url: https://paulrjohnson.net
  description: A Data Scientist Using Causal Inference & Machine Learning to Confirm His Priors.
  favicon: assets/icons/favicon.ico
  search: false
  page-navigation: true
  back-to-top-navigation: false
  twitter-card: true
  open-graph: true
  image: assets/images/me/headshot_rounded.webp
  image-alt: Me looking handsome as hell
  comments: false
  navbar:
    title: P(Johnson) > 0.05
    logo: assets/icons/favicon-36x36.webp
    logo-alt: Purple Octopus
    tools:
      - icon: github
        aria-label: GitHub
        href: https://www.github.com/paulj1989/paulrjohnson.net
      - icon: cup-hot-fill
        aria-label: Buy Me a Coffee
        href: https://www.buymeacoffee.com/paulj1989
    right:
      - text: Blog
        aria-label: Blog
        href: blog/index.qmd
      - text: Projects
        aria-label: Project Portfolio
        href: projects/index.qmd
      - text: Consultancy
        aria-label: Consultancy Enquiries
        href: consultancy/index.qmd
      - text: Curriculum Vitae
        aria-label: Curriculum Vitae
        href: cv/index.qmd
  page-footer:
    left: 2024 Paul Johnson &#8729; Made with [Quarto](https://quarto.org)
    right:
      - text: Contact
        aria-label: Contact Form
        href: contact.qmd
      - text: License
        aria-label: License Details
        href: license.qmd

format:
  html:
    theme:
      - cosmo
      - theme.scss
    highlight-style: assets/github-plus.theme
    fig-align: center
    # lightbox: true
    fig-width: 7
    fig-height: 5
    fig-dpi: 150
    fig-responsive: true
    mainfont: "Poppins"
    monofont: "Fira Code"
    mermaid:
      theme: neutral

knitr:
  opts_chunk:
    dev: ragg_png

execute:
  freeze: auto
  warning: false
  error: false

include-in-header:
  - _includes/umami.html
  - _includes/performance-headers.html
  - _includes/preload-fonts.html
