baseURL: "https://paulrjohnson.net"
title: Paul Johnson
paginate: 10
permalinks:
  posts: /:year/:month/:title/

# Modules
module:
  imports:
    # project theme
    - path: github.com/adityatelange/hugo-PaperMod


enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

ignoreFiles: [ "\\.qmd$", "\\.ipynb$" ]

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Paul Johnson
  description: "Data Scientist"
  keywords: [Blog, Portfolio, PaperMod]
  # author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "images/favicon/octopus-favicon.ico"
    favicon16x16: "images/favicon/octopus-favicon-16x16.png"
    favicon32x32: "images/favicon/octopus-favicon-32x32.png"
    apple_touch_icon: "images/favicon/octopus-apple-touch-icon.png"
    safari_pinned_tab: "images/favicon/octopus-apple-touch-icon.png"

  label:
    text: "Paul Johnson"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Paul Johnson
    subtitle: "A Data Scientist Using Causal Inference & Machine Learning to Confirm All His Priors"
    imageUrl: "images/paul_medium.png"
    imageWidth: 360
    imageHeight: 360
    imageTitle: Paul
    # buttons:
    #   - name: About
    #     url: about
    #   - name: Research
    #     url: research
    #   - name: Blog
    #     url: posts
    #   - name: CV
    #     url: cv

  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/paul_johnson89"
    - name: mastodon
      url: "https://mastodon.social/@paulj1989"
    - name: linkedin
      url: "https://linkedin.com/paulj1989"
    - name: github
      url: "https://github.com/paulj1989"
    - name: stackoverflow
      url: "https://stats.stackexchange.com/users/320054/paul-johnson"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/paulrjohnson.net/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 20
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 30
    - identifier: cv
      name: CV
      url: "https://www.paulrjohnson.net/cv"
      weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
pygmentsCodeFences: true
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: false
    noHl: false
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true
