baseURL = "https://paulrjohnson.net"
languageCode = "en-us"
title = "Paul Johnson"
theme = "cactus"
# googleAnalytics = "UA-191373128-1"

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Research"
url = "/research"
weight = 3

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 4

[[menu.main]]
name = "CV"
url = "/cv"
weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

[params]

  colortheme = "light" # dark, light, white, or classic
  rss = false # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "I'm Paul, a data scientist based in London, currently working in population health management at the NHS. I became a data scientist after leaving academia to pursue a field that gives me the opportunity to use my skill set to have a more direct impact on the world. I'm interested in combining my quantitative social science background with the application of machine learning and deep learning, to understand and predict human behavior and the social world."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 3 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/paulj1989" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/paulj1989"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/paulj1989/"
  [[params.social]]
    name = "twitter"
    link = "https://www.twitter.com/paul_johnson89"
  [[params.social]]
    name = "email"
    link = "paul@paulrjohnson.net"  # no need for "mailto:" in the head
