---
title: Paul Johnson
subtitle: Data Scientist with Experience Across Social Science & Healthcare
pagetitle: Curriculum Vitae | Paul Johnson
description-meta: |
  I am a data scientist with over eight years of experience applying causal
  inference, statistics, and machine learning to human problems across social
  science and healthcare.
css:
  - ../assets/css/cv.css
format:
  html: default
  pdf:
    pdf-engine: wkhtmltopdf
---

## Selected Work Experience  {{< fa briefcase >}}

### Principal Data Scientist

_NHS South, Central and West CSU_ [Nov 2021 --- Present]{.cvdate}

- Providing technical expertise in analytics and research-focused projects across the organisation, including experimental and observational analysis of healthcare interventions.
- Developing and deploying machine learning models, such as forecasting daily event counts in Urgent and Emergency Care Services and a clustering model identifying similar GP practices.
- Leading the development of organisational expertise in data science, including training and mentoring colleagues in statistics, machine learning, and programming.
- Supporting the development of SCW's infrastructure for developing and deploying data science.

### Associate BI Consultant

_NHS South, Central and West CSU_ [April 2021 --- Nov 2021]{.cvdate}

- Led research on wider determinants of health inequalities and the role of deprivation in health outcomes.
- Supported the Population Health Analytics team with research design, statistical modelling, and the visualisation and communication of findings.

### Graduate Research/Teaching Assistant

_University of Houston_ [July 2017 --- Dec 2020]{.cvdate}

- Built natural language processing models for research into political language in legal texts.
- Supported the Political Party Database Project in the administration of the expert survey and maintenance of the project website.
- Assisted in teaching courses, including Intro to Comparative Politics, Mexican Politics, Comparative Elections, and Media & Politics.

### Fundraising Manager: Product Innovation

_Marie Curie_ [Aug 2016 --- July 2017]{.cvdate}

- Managed Marie Curie’s largest regular fundraising campaign (Fundraising My Way), resulting in a significant increase in donations compared to the previous year.
- Assisted in the development of new fundraising products and the innovation of existing campaigns.

### Events & Corporate Fundraiser

_World Child Cancer_ [July 2015 --- April 2016]{.cvdate}

- Developed, recruited, and managed the charity’s largest fundraising event to date (Kilimanjaro trek) and various major events (Ride 100, Great North Run), significantly contributing to fundraising efforts.
- Supported the Head of Corporate Fundraising in successful corporate partnerships, enhancing the charity's fundraising initiatives.

## Further Work Experience  {{< fa clock-rotate-left >}}

### Various Administrative Roles

_Charity Sector & NHS_

- Family for Every Child – Events Coordinator
- University Hospital Southampton – Oncology Outpatient Clerk
- University Hospital Southampton – Income Management Assistant

## Education  {{< fa graduation-cap >}}

**M.A. Political Science**
\
*University of Houston* [*2017 --- 2020*]{.cvdate}
\
\
**M.Sc. Global Politics**
\
*University of Southampton* [*2011 --- 2012*]{.cvdate}
\
\
**B.A. Politics**
\
*University of Sussex* [*2008 --- 2011*]{.cvdate}
\

::: {.content-visible when-format="pdf"}

## References
Available upon request.

:::
