{
  "hash": "646dcde2e00aaeefe575d9d9aec5cd5a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: |\n  Calculating a Football Team's Strength of Schedule\nsubtitle: |\n  It may not be the metric you want, but it's also not the metric you need.\ndescription-meta: |\n  Developing a Strength of Schedule model for football, using the final games of \n  the 2023/24 season in the Premier League & the Championship as case studies.\nauthor: Paul Johnson\ndate: 2024-04-02\nimage: scoreboard.webp\nimage-alt: |\n  A photo of a black and white scoreboard with orange text, in Russian, on a \n  rusted metal frame, in a built up urban environment, with a white and blue \n  concrete building filling the background.\ncategories: [Football Analytics, Statistics, R]\nbibliography: references.bib\n---\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Setup Code (Click to Expand)\"}\n# import packages\nsuppressPackageStartupMessages({\n  library(dplyr)\n  library(gt)\n  library(ggplot2)\n})\n\n# setup fonts\nsysfonts::font_add_google(\"Poppins\")\nsysfonts::font_add_google(\"Lora\")\nshowtext::showtext_auto()\n\n# set plot theme\n# inspired by https://github.com/z3tt/TidyTuesday/blob/main/R/2020_31_PalmerPenguins.Rmd\ntheme_set(theme_minimal(base_size = 20, base_family = \"Poppins\")) +\n  theme_update(\n    panel.grid.major = element_line(color = \"grey90\", linewidth = .4),\n    panel.grid.minor = element_blank(),\n    axis.title.x = element_text(\n      color = \"grey30\", margin = margin(t = 5), size = rel(1.05)\n    ),\n    axis.title.y = element_text(\n      color = \"grey30\", margin = margin(r = 5), size = rel(1.05)\n    ),\n    axis.text.x = element_text(color = \"grey50\", size = rel(1)),\n    axis.text.y = element_text(\n      colour = \"grey30\", size = rel(1.15), hjust = 0.5, lineheight = .4\n      ),\n    axis.ticks.x = element_line(color = \"grey90\", linewidth = .4),\n    axis.ticks.y = element_blank(),\n    axis.ticks.length = unit(.2, \"lines\"),\n    legend.position = \"top\",\n    legend.title = element_blank(),\n    legend.text = element_text(size = rel(1)),\n    plot.title = element_text(\n      hjust = 0, color = \"black\", family = \"Lora\",\n      size = rel(1.5), margin = margin(t = 5, b = 5)\n    ),\n    plot.subtitle = element_text(\n      hjust = 0, color = \"grey30\", family = \"Lora\",\n      lineheight = 0.5, size = rel(1.1),\n      margin = margin(5, 0, 5, 0)\n    ),\n    plot.title.position = \"plot\",\n    plot.caption = element_text(\n      color = \"grey50\", size = rel(0.8), hjust = 1,\n      margin = margin(10, 0, 0, 0)\n    ),\n    plot.caption.position = \"plot\",\n    plot.margin = margin(rep(10, 4))\n  )\n\n# set gt theme\ntbl_theme <- \n  function(data, type = c(\"num\", \"pct\"), .round = 2, ...) {\n    if (type == \"num\") {\n      data |>\n        cols_align(columns = is.numeric, align = \"center\") |>\n        fmt_number(\n          columns = is.numeric, decimals = .round, drop_trailing_zeros = TRUE\n        ) |> \n        tab_source_note(source_note = \"Source: FBref Via {worldfootballR}\") |>\n        tab_options(\n          table.width = pct(100),\n          table.font.names = \"Poppins\",\n          ...\n        ) |>\n        tab_style(\n          style = cell_text(align = \"left\"),\n          locations = list(cells_source_notes(), cells_footnotes())\n        )\n    } else if (type == \"pct\") {\n      data |>\n        cols_align(columns = is.numeric, align = \"center\") |>\n        fmt_percent(\n          columns = is.numeric, decimals = .round, drop_trailing_zeros = TRUE\n        ) |> \n        tab_source_note(source_note = \"Source: FBref Via {worldfootballR}\") |>\n        tab_options(\n          table.width = pct(100),\n          table.font.names = \"Poppins\",\n          ...\n        ) |>\n        tab_style(\n          style = cell_text(align = \"left\"),\n          locations = list(cells_source_notes(), cells_footnotes())\n        )\n    } else {\n      stop(\"type must equal `num` or `pct`\")\n    }\n  }\n```\n:::\n\n\n\nAmerican sports fans love numbers. Europeans are all vibes. Fighting and vibes. The American Soccer^[If anyone wants to complain about it being called soccer, then please a) grow up, and b) go look at who first came up with that term.] Revolution of the late '00s and early '10s brought a sea of nerds armed with calculators, ready to formalise the sport with mathematical proofs. So came the birth of a new era of football, where we rid ourselves of the shackles of _Actually Watching Games_ and studied the sport in its purest form, the spreadsheet.\n\nAnalytics has become a permanent fixture in football, with every club having teams of analysts to scout players and opponents and measure performance. Metrics like expected goals (xG) are increasingly common in football media coverage. America's finest nerds have spent years devising ways to explain this silly little sport to the unwashed European masses, including leaning on existing concepts and ideas in American sports to build metrics that help explain football in valuable ways. \n\nHowever, a standard metric that has remained relatively untouched is the strength of schedule (SOS). SOS measures the quality of the opponents a team has faced or will face to account for the difficulty of a team's schedule when judging past performances or predicting future outcomes. \n\nWhile SOS is less useful in European sports, where leagues are generally structured so that every team has an equal schedule, it can still be helpful when trying to say meaningful things about what has or will happen, both in domestic leagues and continental (and international) knockout tournaments.\n\nI will develop a simple method for measuring SOS that can be easily implemented and interpreted. I hope my ideas become pervasive like the American Soccer Nerds all around us.\n\n## A Simple Approach to Measuring Schedule Strength {#sec-methodology}\n\nMy goal with developing an SOS metric for football is to create something relatively simple but still does a solid job of capturing schedule difficulty. I'm sure there will be more precise ways to get at this, but I want to maximise the precision while maintaining simplicity in both implementation and interpretation. For something like this, a decent metric that is really easy to use is much better than a really accurate metric that is particularly complex for anyone looking to use or understand it.\n\nThe simplest approach to measuring schedule difficulty is to use the winning record of a team's opponents to capture how well the team's opponents have been doing in the league that season. For example, the [Wikipedia entry](https://en.wikipedia.org/wiki/Strength_of_schedule) for Strength of Schedule lists the following formula:\n\n$$SOS = \\frac{2(OR) + (OOR)}{3}$$\nwhere OR is the opponents' winning record, and OOR is the opponents' opponents winning record. There are many variants to this, some more complex than others^[I'm not claiming to be an expert in the various ways SOS is calculated in American sports, so if you're after a detailed literature review, I'm afraid you've come to the wrong place.], but the fundamental issue with this approach is that wins and losses are all counted equally. A win over some garbage team (for example, Portsmouth FC) means just the same as a way against a heavyweight (for instance, Southampton FC). I like the approach to capturing the inequality in the quality of the teams that a team's opponents have played, but the issues with using winning records are insurmountable.\n\n### Calculating Baseline Team Ratings {#sec-ratings-methodology}\n\nInstead, measuring the difficulty of a team's schedule should start with making at least a half-decent effort to quantify each opponent's strength. I will calculate a relatively crude measure of baseline team ratings using non-penalty goal difference per 90 (npG/90) and non-penalty expected goal difference per 90 (npxGD/90)^[There are, however, lots of ways of approaching this [@torvaney2021ratings; @caley2023].]. \n\nI will take a weighted combination of npxGD/90 (70%) and npGD/90 (30%) because previous work suggests this is the optimal way to combine the two [@torvaney2021xg]. \n\n<details>\n<summary>Notation[^notation] (Click to Expand)</summary>\n\n\n$$ R_i = (0.7 \\cdot \\text{npxG}_{i_{\\text{/90}}}) + (0.3 \\cdot \\text{npG}_{i_{\\text{/90}}})\n $$\n\n</details>\n\nThis approach benefits from conceptual simplicity, making for a relatively straightforward interpretation. \n\n[^notation]: \n\n    I have included notation for each step in building the model, but I have hidden it \n    because it isn't necessary to understand the methodology. It's just there for the sickos.\n\n### Estimating Home Advantage\n\nRather than making wild assumptions about home advantage, I decided to do the responsible thing: measure the average home advantage across the big five leagues in recent seasons and use that number to weight home games. \n\nI used the excellent [**worldfootballR**](https://jaseziv.github.io/worldfootballR) package to grab match results data in the big five leagues from 2017/18 to 2022/23 from [FBref](https://FBref.com/) focusing on actual and expected goals (because penalties are relevant when measuring home advantage). I have also dropped any rows where attendance is NA, assuming that NAs represent empty stadiums, particularly during the COVID-19 pandemic.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Data Code (Click to Expand)\"}\nhome_and_away <-\n  worldfootballR::fb_match_results(\n    country = c(\"ENG\", \"FRA\", \"ESP\", \"GER\", \"ITA\"),\n    season_end_year = 2018:2023,\n    gender = \"M\"\n  ) |>\n  janitor::clean_names(\n    replace = c(\"xG\" = \"xg\")\n  ) |>\n  mutate(\n    league = case_when(\n      competition_name == \"Fußball-Bundesliga\" ~ \"Bundesliga\",\n      .default = competition_name\n    )\n  ) |>\n  select(league, ends_with(\"_goals\"), ends_with(\"_xg\"), attendance) |>\n  tidyr::drop_na()\n```\n:::\n\n\n\n@tbl-home-advantage shows the league average percentage difference in goals scored by home teams compared with away teams, and the average for the big five leagues is calculated, too.\n\n\n\n::: {#tbl-home-advantage .cell tbl-cap='Average Home Advantage in the Big Five Leagues 2017/18 - 2022/23\n'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Table Code (Click to Expand)\"}\nhome_and_away |>\n  tidyr::drop_na() |>\n  bind_rows(\n    home_and_away |>\n      summarise(\n        across(ends_with(\"_goals\") | ends_with(\"_xg\"), mean)\n      ) |>\n      mutate(\"league\" = \"Big Five Leagues\")\n  ) |>\n  summarise(\n    across(ends_with(\"_goals\") | ends_with(\"_xg\"), mean),\n    .by = c(league)\n  ) |>\n  mutate(\n    goal_diff = (home_goals - away_goals) / away_goals,\n    xg_diff = (home_xg - away_xg) / away_xg\n  ) |>\n  select(league, goal_diff, xg_diff) |>\n  rename(\n    \"League\" = \"league\",\n    \"Goals\" = \"goal_diff\",\n    \"Expected Goals\" = \"xg_diff\"\n  ) |>\n  gt() |>\n  tab_spanner(\n    label = \"Difference (Home vs Away)\",\n    columns = 2:3\n  ) |>\n  tab_footnote(\"Excluding games played without fans in attendance.\") |>\n  tab_style(\n    style = list(cell_text(weight = \"bold\")),\n    locations = cells_body(\n      columns = everything(),\n      rows = League == \"Big Five Leagues\"\n    )\n  ) |> \n  tbl_theme(type = \"pct\", .round = 1)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xhbnzyqtfl\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xhbnzyqtfl table {\n  font-family: Poppins;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xhbnzyqtfl thead, #xhbnzyqtfl tbody, #xhbnzyqtfl tfoot, #xhbnzyqtfl tr, #xhbnzyqtfl td, #xhbnzyqtfl th {\n  border-style: none;\n}\n\n#xhbnzyqtfl p {\n  margin: 0;\n  padding: 0;\n}\n\n#xhbnzyqtfl .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xhbnzyqtfl .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xhbnzyqtfl .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xhbnzyqtfl .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xhbnzyqtfl .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xhbnzyqtfl .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xhbnzyqtfl .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xhbnzyqtfl .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xhbnzyqtfl .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xhbnzyqtfl .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xhbnzyqtfl .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xhbnzyqtfl .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xhbnzyqtfl .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xhbnzyqtfl .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xhbnzyqtfl .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xhbnzyqtfl .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xhbnzyqtfl .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xhbnzyqtfl .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xhbnzyqtfl .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xhbnzyqtfl .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xhbnzyqtfl .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xhbnzyqtfl .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xhbnzyqtfl .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xhbnzyqtfl .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xhbnzyqtfl .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xhbnzyqtfl .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xhbnzyqtfl .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xhbnzyqtfl .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xhbnzyqtfl .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xhbnzyqtfl .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xhbnzyqtfl .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xhbnzyqtfl .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xhbnzyqtfl .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xhbnzyqtfl .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xhbnzyqtfl .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xhbnzyqtfl .gt_left {\n  text-align: left;\n}\n\n#xhbnzyqtfl .gt_center {\n  text-align: center;\n}\n\n#xhbnzyqtfl .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xhbnzyqtfl .gt_font_normal {\n  font-weight: normal;\n}\n\n#xhbnzyqtfl .gt_font_bold {\n  font-weight: bold;\n}\n\n#xhbnzyqtfl .gt_font_italic {\n  font-style: italic;\n}\n\n#xhbnzyqtfl .gt_super {\n  font-size: 65%;\n}\n\n#xhbnzyqtfl .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xhbnzyqtfl .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xhbnzyqtfl .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xhbnzyqtfl .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xhbnzyqtfl .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xhbnzyqtfl .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xhbnzyqtfl .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xhbnzyqtfl .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xhbnzyqtfl div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"League\">League</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"Difference (Home vs Away)\">\n        <span class=\"gt_column_spanner\">Difference (Home vs Away)</span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Goals\">Goals</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Expected Goals\">Expected Goals</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"League\" class=\"gt_row gt_left\">Premier League</td>\n<td headers=\"Goals\" class=\"gt_row gt_center\">26.6%</td>\n<td headers=\"Expected Goals\" class=\"gt_row gt_center\">24.3%</td></tr>\n    <tr><td headers=\"League\" class=\"gt_row gt_left\">La Liga</td>\n<td headers=\"Goals\" class=\"gt_row gt_center\">35.1%</td>\n<td headers=\"Expected Goals\" class=\"gt_row gt_center\">34.8%</td></tr>\n    <tr><td headers=\"League\" class=\"gt_row gt_left\">Ligue 1</td>\n<td headers=\"Goals\" class=\"gt_row gt_center\">28.7%</td>\n<td headers=\"Expected Goals\" class=\"gt_row gt_center\">24.9%</td></tr>\n    <tr><td headers=\"League\" class=\"gt_row gt_left\">Bundesliga</td>\n<td headers=\"Goals\" class=\"gt_row gt_center\">30.2%</td>\n<td headers=\"Expected Goals\" class=\"gt_row gt_center\">24.6%</td></tr>\n    <tr><td headers=\"League\" class=\"gt_row gt_left\">Serie A</td>\n<td headers=\"Goals\" class=\"gt_row gt_center\">17.8%</td>\n<td headers=\"Expected Goals\" class=\"gt_row gt_center\">18.7%</td></tr>\n    <tr><td headers=\"League\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Big Five Leagues</td>\n<td headers=\"Goals\" class=\"gt_row gt_center\" style=\"font-weight: bold;\">27.4%</td>\n<td headers=\"Expected Goals\" class=\"gt_row gt_center\" style=\"font-weight: bold;\">25.3%</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" style=\"text-align: left;\" colspan=\"3\">Source: FBref Via {worldfootballR}</td>\n    </tr>\n  </tfoot>\n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" style=\"text-align: left;\" colspan=\"3\"> Excluding games played without fans in attendance.</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nThe variance in the percentage difference in both goals and expected goals in @tbl-home-advantage is pretty high, though that does appear to be driven by Serie A and La Liga being at the extreme ends. The Premier League, Bundesliga, and Ligue 1 variance is significantly lower. This is interesting, but I will avoid going down this specific rabbit hole right now because rabbit hole inception is a step too far. \n\nI'm doing my duty as a Brexit-era Englishman focusing only on English leagues and pretending that football does not exist outside these fair shores. Taking the average across the big five leagues is acceptable for these purposes. Although the average is just above 25% for both goals and expected goals, I'm not going to be an insufferable bore^[I mean, clearly, that's not true. This blog post would not exist if I wasn't an insufferable bore. But even I have my limits.]. I will treat the home advantage as 25% to keep things simple.\n\nTeam ratings will be weighted by home advantage by adding 25% of the team rating's absolute value to the rating. \n\n<details>\n<summary>Notation (Click to Expand)</summary>\n\n$$\nR_{ij} = \\\\\n\\begin{cases} \n  R_j + |R_j| \\cdot H & \\text{if game is at opponent's home} \\\\ \n  R_j & \\text{otherwise} \n\\end{cases}\n$$\nwhere $R_{ij}$ is the opponent team's rating, $R_j$ is their baseline rating (with $|R_j|$ representing the absolute value of the opponent's baseline rating), and $H$ is the home advantage weighting.\n\n</details>\n\n### Putting it All Together {#sec-sos-methodology}\n\nWe should now be able to assemble everything to create an SOS model.\n\nThe first step is to calculate the opponents' ratings (OR) and the opponents' opponents' ratings (OOR)^[My main reason for abbreviating this is because writing this multiple times (and not messing up the punctuation) was intolerable.]. I will do this by first calculating the weighted team rating for each fixture, meaning that when a team plays away from home OR will be 25% higher and when they are at home, OOR is 25% higher. I will then take the mean value of OR and OOR. This second value is more involved, but it is conceptually the same as the mean value of OR. \n\n<details>\n<summary>Notation (Click to Expand)</summary>\n\n$$ \\hat{OR}_i = \\frac{1}{n} \\sum_{j=1}^n { R_{ij}^\\prime } $$\nwhere $\\hat{OR}_i$ is the mean average opponents' ratings for team $i$, $n$ is the total number of opponents that team $i$ faces, and $R_{ij}^\\prime$ denotes the adjusted rating of opponent $j$ when playing against team $i$, accounting for the home advantage. \n\nA similar process can also be carried out to calculate team $i$'s OOR ($OOR_i$). However, you have to calculate the ratings for each of team $i$'s opponents' opponents, then take the mean average value for each opponent's schedule, and then the mean average for all of team $i$'s opponents.\n\n$$  { \\hat{OOR}_i = \\frac{1}{n} \\sum_{j=1}^{n} \\left( \\frac{1}{m_j} \\sum_{k=1}^{m_j} R_{jk}^\\prime \\right) } $$\n\nwhere $\\hat{OOR}_i$ represents the mean value of team $i$'s OOR, $n$ is the total opponents, $m_j$ is the total number of opponents for opponent $j$ of team $i$, and $R_{jk}^\\prime$ is the rating of opponent $k$ when playing against opponent $j$ of team $i$. \n\nThe outer sum iterates over each opponent of team $i$, and for each opponent $j$, while the inner sum calculates the mean rating of their opponents (opponents of opponent $j$). Finally, the outer sum computes the mean value of these mean ratings over all opponents of team $i$.\n\n</details>\n\nThe average value of a team's OR and OOR play slightly different roles in the model. OR is the model's primary parameter, and OOR provides additional context, allowing us to weight OR by the quality of the opponents' opposition. \n\nI will take a weighted average of OR (66.6%) and OOR (33.3%) and sum the two values.  \n\n<details>\n<summary>Notation (Click to Expand)</summary>\n\nUsing the values $OR_i$ and $OOR_i$, we can calculate the strength of schedule for team $i$ by weighting the two ratings.\n\n$$ SOS_i = (\\frac{2}{3} \\cdot OR_i) + (\\frac{1}{3} \\cdot OOR_i)$$\n</details>\n\nWhile this approach yields a defensible SOS metric, the interpretability of the results may be limited. I have concerns about the practical significance of SOS values measured on the same scale as goals per 90. What does it mean for a team to have a one-goal-per-90 advantage in SOS? Are unit increases and decreases in SOS linear across the range of values? I think using the same scale as goals per 90 may lead to oversimplification and potential misinterpretation of SOS values^[I'm unsure if my concerns are warranted. I may be overthinking things. Feedback is welcome!].\n\nInstead, transforming SOS onto a standard scale, such as z-scores, offers a solution. Z-scores provide a standardised measure that facilitates precise comparative analysis across teams or seasons. This approach makes the results easier to interpret and allows for more meaningful comparisons within the league context. \n\nSOS z-scores are calculated by taking the mean average and standard deviation of SOS for the entire league. For each unstandardised value of SOS, we subtract the mean and divide the result by the standard deviation. \n\n<details>\n<summary>Notation (Click to Expand)</summary>\n\n$$ SOS_i^\\prime = \\frac{SOS_i - \\mu_{SOS}} {\\sigma_{SOS}} $$\nwhere $SOS_i^\\prime$ is the standardised SOS z-score for team $i$, while $\\mu_{SOS}$ is the mean value of all SOS and $\\sigma_{SOS}$ is the standard deviation of all SOS. \n\n</details>\n\nAn SOS that equals zero is a league-average schedule; scores greater than zero are harder than the league average, and scores less than zero are easier than the league average. If a team's SOS z-score is +1, their SOS is one standard deviation above the average SOS for all teams. Similarly, a z-score of -1 indicates that the SOS is one standard deviation below the average. Z-scores allow us to compare different teams' SOS values on a standard scale, making it easier to interpret and analyse their relative strengths of schedule.\n\n## Premier League Strength of Schedule\n\nThe upside of Sunday's dull 0-0 draw between Man City and Arsenal is that this was the ideal result for extending this incredible three-way title race in the Premier League. This is precisely the situation where a quantitative measure of the difficulty of each team's schedule down the stretch would be valuable. Sounds like the perfect way to test this metric! I grabbed team-level goals and expected goals data and match results for the 2023/24 season in the Premier League from FBref via **worldfootballR**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Data Code (Click to Expand)\"}\nmatch_results_raw <-\n  worldfootballR::fb_match_results(\n    country = \"ENG\", gender = \"M\", season_end_year = 2024\n  )\n\nteam_stats_raw <-\n  worldfootballR::fb_season_team_stats(\n    country = \"ENG\", gender = \"M\", season_end_year = 2024,\n    stat_type = \"standard\", tier = \"1st\"\n  )\n```\n:::\n\n\n\nI have also turned all of this into an R package, [**fitba**](https://paulj1989.github.io/fitba/)^[**F**unctions **I**n**T**ended for foot**B**all **A**nalytics... Yes, I'm an idiot]. This should also make it easier for anyone to use this code and build on the method.\n\n### Remaining Schedule\n\nThe first step is to filter the match results data to only include the remaining games we want to work with. We can leverage that **worldfootballR**'s `fb_match_results()` function also includes future games with undetermined details about the match, like home and away goals, set to NA.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nremaining_games <-\n  match_results_raw |>\n  janitor::clean_names() |> \n  filter(is.na(home_goals) | is.na(away_goals)) |>\n  mutate(\n    team = home,\n    opponent = away,\n    home_or_away = \"Home\"\n  ) |>\n  bind_rows(\n    match_results_raw |>\n      janitor::clean_names() |> \n      filter(is.na(home_goals) | is.na(away_goals)) |>\n      mutate(\n        team = away,\n        opponent = home,\n        home_or_away = \"Away\"\n      )\n  ) |>\n  select(team, home_or_away, opponent)\n```\n:::\n\n\n\nThis creates a dataframe with every remaining fixture in the 2023/24 Premier League season repeated twice, with each team listed once in the `team` and `opponent` columns. @tbl-schedule, below, shows a sample of the data.\n\n\n\n::: {#tbl-schedule .cell tbl-cap='Sample of Remaining Premier League Fixtures\n'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Table Code (Click to Expand)\"}\nremaining_games |> \n  janitor::clean_names(case = \"title\") |> \n  slice_sample(n = 10) |> \n  gt() |> \n  tbl_theme(type = \"num\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"nvcmjfvnke\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nvcmjfvnke table {\n  font-family: Poppins;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nvcmjfvnke thead, #nvcmjfvnke tbody, #nvcmjfvnke tfoot, #nvcmjfvnke tr, #nvcmjfvnke td, #nvcmjfvnke th {\n  border-style: none;\n}\n\n#nvcmjfvnke p {\n  margin: 0;\n  padding: 0;\n}\n\n#nvcmjfvnke .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nvcmjfvnke .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nvcmjfvnke .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nvcmjfvnke .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nvcmjfvnke .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nvcmjfvnke .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nvcmjfvnke .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nvcmjfvnke .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nvcmjfvnke .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nvcmjfvnke .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nvcmjfvnke .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nvcmjfvnke .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nvcmjfvnke .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nvcmjfvnke .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nvcmjfvnke .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nvcmjfvnke .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nvcmjfvnke .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nvcmjfvnke .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nvcmjfvnke .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nvcmjfvnke .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nvcmjfvnke .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nvcmjfvnke .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nvcmjfvnke .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nvcmjfvnke .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nvcmjfvnke .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nvcmjfvnke .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nvcmjfvnke .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nvcmjfvnke .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nvcmjfvnke .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nvcmjfvnke .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nvcmjfvnke .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nvcmjfvnke .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nvcmjfvnke .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nvcmjfvnke .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nvcmjfvnke .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nvcmjfvnke .gt_left {\n  text-align: left;\n}\n\n#nvcmjfvnke .gt_center {\n  text-align: center;\n}\n\n#nvcmjfvnke .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nvcmjfvnke .gt_font_normal {\n  font-weight: normal;\n}\n\n#nvcmjfvnke .gt_font_bold {\n  font-weight: bold;\n}\n\n#nvcmjfvnke .gt_font_italic {\n  font-style: italic;\n}\n\n#nvcmjfvnke .gt_super {\n  font-size: 65%;\n}\n\n#nvcmjfvnke .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nvcmjfvnke .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nvcmjfvnke .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nvcmjfvnke .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nvcmjfvnke .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nvcmjfvnke .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nvcmjfvnke .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#nvcmjfvnke .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#nvcmjfvnke div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Team\">Team</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Home or Away\">Home or Away</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Opponent\">Opponent</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Manchester Utd</td>\n<td headers=\"Home or Away\" class=\"gt_row gt_left\">Home</td>\n<td headers=\"Opponent\" class=\"gt_row gt_left\">Liverpool</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Bournemouth</td>\n<td headers=\"Home or Away\" class=\"gt_row gt_left\">Home</td>\n<td headers=\"Opponent\" class=\"gt_row gt_left\">Crystal Palace</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Manchester City</td>\n<td headers=\"Home or Away\" class=\"gt_row gt_left\">Away</td>\n<td headers=\"Opponent\" class=\"gt_row gt_left\">Tottenham</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Brentford</td>\n<td headers=\"Home or Away\" class=\"gt_row gt_left\">Away</td>\n<td headers=\"Opponent\" class=\"gt_row gt_left\">Aston Villa</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Crystal Palace</td>\n<td headers=\"Home or Away\" class=\"gt_row gt_left\">Home</td>\n<td headers=\"Opponent\" class=\"gt_row gt_left\">Newcastle Utd</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Everton</td>\n<td headers=\"Home or Away\" class=\"gt_row gt_left\">Home</td>\n<td headers=\"Opponent\" class=\"gt_row gt_left\">Nott'ham Forest</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Manchester City</td>\n<td headers=\"Home or Away\" class=\"gt_row gt_left\">Away</td>\n<td headers=\"Opponent\" class=\"gt_row gt_left\">Brighton</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Luton Town</td>\n<td headers=\"Home or Away\" class=\"gt_row gt_left\">Home</td>\n<td headers=\"Opponent\" class=\"gt_row gt_left\">Fulham</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Nott'ham Forest</td>\n<td headers=\"Home or Away\" class=\"gt_row gt_left\">Home</td>\n<td headers=\"Opponent\" class=\"gt_row gt_left\">Manchester City</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Liverpool</td>\n<td headers=\"Home or Away\" class=\"gt_row gt_left\">Home</td>\n<td headers=\"Opponent\" class=\"gt_row gt_left\">Tottenham</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" style=\"text-align: left;\" colspan=\"3\">Source: FBref Via {worldfootballR}</td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nTo me, this seems like the obvious way to structure the data, but it's important to remember that I am an idiot, so there may well be a better way.\n\n### Baseline Team Ratings {#sec-team-ratings}\n\nThe next step is to create the baseline ratings for each Premier League team using their npxGD/90 and npGD/90. As discussed in @sec-methodology, calculating the team ratings is very simple. They are just a weighted average of npxGD/90 (70%) and npGD/90 (30%). \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nratings <-\n  team_stats_raw |>\n  janitor::clean_names(\n    replace = c(\n      \"Squad\" = \"team\",\n      \"_Expected\" = \"\",\n      \"G_minus_PK\" = \"npg\",\n      \"npxG\" = \"npxg\",\n      \"_Per_Minutes\" = \"90\"\n    )\n  ) |>\n  select(team, team_or_opponent, npxg90, npg90) |>\n  mutate(team = stringr::str_remove(team, \"vs \")) |>\n  tidyr::pivot_wider(\n    names_from = team_or_opponent,\n    values_from = c(npg90, npxg90),\n    names_glue = \"{team_or_opponent}_{.value}\"\n  ) |>\n  summarise(\n    npxgd90 = team_npxg90 - opponent_npxg90,\n    npgd90 = team_npg90 - opponent_npg90,\n    rating = (npxgd90 * 0.7) + (npgd90 * 0.3),\n    .by = team\n  )\n```\n:::\n\n\n\nThe ratings in @tbl-team-ratings show each Premier League team's npxGD/90, npGD/90, and baseline ratings, arranged from highest to lowest. \n\n\n\n::: {#tbl-team-ratings .cell tbl-cap='Baseline Team Ratings in the Premier League\n'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Table Code (Click to Expand)\"}\nratings |> \n  arrange(desc(rating)) |> \n  janitor::clean_names(case = \"title\") |> \n  rename(\n    \"npxGD/90\" = Npxgd90,\n    \"npGD/90\" = Npgd90\n  ) |> \n  gt() |> \n  tbl_theme(type = \"num\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ugkpdbjxgn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ugkpdbjxgn table {\n  font-family: Poppins;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ugkpdbjxgn thead, #ugkpdbjxgn tbody, #ugkpdbjxgn tfoot, #ugkpdbjxgn tr, #ugkpdbjxgn td, #ugkpdbjxgn th {\n  border-style: none;\n}\n\n#ugkpdbjxgn p {\n  margin: 0;\n  padding: 0;\n}\n\n#ugkpdbjxgn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ugkpdbjxgn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ugkpdbjxgn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ugkpdbjxgn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ugkpdbjxgn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ugkpdbjxgn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ugkpdbjxgn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ugkpdbjxgn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ugkpdbjxgn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ugkpdbjxgn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ugkpdbjxgn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ugkpdbjxgn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ugkpdbjxgn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ugkpdbjxgn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ugkpdbjxgn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ugkpdbjxgn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ugkpdbjxgn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ugkpdbjxgn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ugkpdbjxgn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ugkpdbjxgn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ugkpdbjxgn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ugkpdbjxgn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ugkpdbjxgn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ugkpdbjxgn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ugkpdbjxgn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ugkpdbjxgn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ugkpdbjxgn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ugkpdbjxgn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ugkpdbjxgn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ugkpdbjxgn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ugkpdbjxgn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ugkpdbjxgn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ugkpdbjxgn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ugkpdbjxgn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ugkpdbjxgn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ugkpdbjxgn .gt_left {\n  text-align: left;\n}\n\n#ugkpdbjxgn .gt_center {\n  text-align: center;\n}\n\n#ugkpdbjxgn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ugkpdbjxgn .gt_font_normal {\n  font-weight: normal;\n}\n\n#ugkpdbjxgn .gt_font_bold {\n  font-weight: bold;\n}\n\n#ugkpdbjxgn .gt_font_italic {\n  font-style: italic;\n}\n\n#ugkpdbjxgn .gt_super {\n  font-size: 65%;\n}\n\n#ugkpdbjxgn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ugkpdbjxgn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ugkpdbjxgn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ugkpdbjxgn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ugkpdbjxgn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ugkpdbjxgn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ugkpdbjxgn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ugkpdbjxgn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ugkpdbjxgn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Team\">Team</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"npxGD/90\">npxGD/90</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"npGD/90\">npGD/90</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Rating\">Rating</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Arsenal</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">1.12</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">1.27</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">1.17</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Manchester City</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.97</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">1.17</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">1.03</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Liverpool</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.85</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">1.14</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.94</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Tottenham</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.3</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.72</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.43</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Aston Villa</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.21</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.53</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.31</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Chelsea</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.34</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.11</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.2</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Brighton</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.17</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.11</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.15</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Everton</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.23</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.04</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.15</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Newcastle Utd</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.08</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.28</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.14</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Bournemouth</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.02</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.25</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.06</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Brentford</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.07</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.5</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.1</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Fulham</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.27</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.2</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.13</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Manchester Utd</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.29</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.2</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">West Ham</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.29</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.2</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Nott'ham Forest</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.14</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.43</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.23</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Wolves</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.28</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.14</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.24</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Crystal Palace</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.26</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.52</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.34</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Burnley</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.72</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.97</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.79</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Luton Town</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.95</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.73</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.88</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Sheffield Utd</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−1.05</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−1.69</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−1.24</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" style=\"text-align: left;\" colspan=\"4\">Source: FBref Via {worldfootballR}</td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nAccording to @tbl-team-ratings, Arsenal are the best team in the league, which seems about right, followed by Manchester City and Liverpool, and then a giant chasm before we reach the rest of the league (which is topped by Tottenham). I am not compelled to argue with these ratings, but if you're a Manchester United fan who doesn't have the capacity for shame, you might?\n\nWe then have to calculate the mean rating for a team's OR and OOR from these baseline ratings. The process for calculating each of these is similar. However, the home advantage weighting is reversed for the OOR, and a little extra work is required to get the opponents that a team's opponents will face. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nopponent_ratings <-\n  remaining_games |>\n  left_join(ratings, by = join_by(opponent == team)) |>\n  mutate(\n    rating =\n      if_else(home_or_away == \"Away\", rating + (abs(rating) * 0.25), rating)\n  ) |>\n  summarise(opponent_rating = mean(rating), .by = team)\n\nopponent_opponent_ratings <-\n  remaining_games |>\n  left_join(ratings, by = join_by(team)) |>\n  mutate(\n    rating =\n      if_else(home_or_away == \"Home\", rating + (abs(rating) * 0.25), rating)\n  ) |>\n  summarise(rating = mean(rating), .by = opponent) |>\n  full_join(remaining_games) |>\n  summarise(opponent_opponent_rating = mean(rating), .by = team)\n```\n:::\n\n\n\n@tbl-opponent-ratings shows the two sets of ratings joined by their corresponding team, which hopefully helps make sense of what is happening here. This part of the process is a little confusing because the steps are kind of stacked on top of each other. Fingers crossed, this makes it easier to follow.\n\n\n\n::: {#tbl-opponent-ratings .cell tbl-cap='Team Opponents\\' & Opponents\\' Oppponents Ratings\n'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Table Code (Click to Expand)\"}\nremaining_games |>\n  distinct(team) |>\n  arrange(team) |> \n  left_join(opponent_ratings, by = join_by(team)) |>\n  left_join(opponent_opponent_ratings, by = join_by(team)) |> \n  rename(\n    \"Team\" = team,\n    \"Opponents' Rating\" = opponent_rating,\n    \"Opponents' Oppponents Rating\" = opponent_opponent_rating,\n  ) |> \n  gt() |> \n  tbl_theme(type = \"num\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jdcmppfnio\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jdcmppfnio table {\n  font-family: Poppins;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jdcmppfnio thead, #jdcmppfnio tbody, #jdcmppfnio tfoot, #jdcmppfnio tr, #jdcmppfnio td, #jdcmppfnio th {\n  border-style: none;\n}\n\n#jdcmppfnio p {\n  margin: 0;\n  padding: 0;\n}\n\n#jdcmppfnio .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jdcmppfnio .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jdcmppfnio .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jdcmppfnio .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jdcmppfnio .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jdcmppfnio .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jdcmppfnio .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jdcmppfnio .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jdcmppfnio .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jdcmppfnio .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jdcmppfnio .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jdcmppfnio .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jdcmppfnio .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jdcmppfnio .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jdcmppfnio .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jdcmppfnio .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jdcmppfnio .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jdcmppfnio .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jdcmppfnio .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jdcmppfnio .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jdcmppfnio .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jdcmppfnio .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jdcmppfnio .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jdcmppfnio .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jdcmppfnio .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jdcmppfnio .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jdcmppfnio .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jdcmppfnio .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jdcmppfnio .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jdcmppfnio .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jdcmppfnio .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jdcmppfnio .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jdcmppfnio .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jdcmppfnio .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jdcmppfnio .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jdcmppfnio .gt_left {\n  text-align: left;\n}\n\n#jdcmppfnio .gt_center {\n  text-align: center;\n}\n\n#jdcmppfnio .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jdcmppfnio .gt_font_normal {\n  font-weight: normal;\n}\n\n#jdcmppfnio .gt_font_bold {\n  font-weight: bold;\n}\n\n#jdcmppfnio .gt_font_italic {\n  font-style: italic;\n}\n\n#jdcmppfnio .gt_super {\n  font-size: 65%;\n}\n\n#jdcmppfnio .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jdcmppfnio .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jdcmppfnio .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jdcmppfnio .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jdcmppfnio .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jdcmppfnio .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jdcmppfnio .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jdcmppfnio .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jdcmppfnio div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Team\">Team</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Opponents' Rating\">Opponents' Rating</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Opponents' Oppponents Rating\">Opponents' Oppponents Rating</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Arsenal</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">0.01</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.17</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Aston Villa</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">0.46</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.03</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Bournemouth</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">0.08</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.15</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Brentford</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">−0.15</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.13</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Brighton</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">0.22</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.02</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Burnley</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">−0.07</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.06</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Chelsea</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">0.1</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.13</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Crystal Palace</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">0.21</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.07</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Everton</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">−0.02</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Fulham</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">0.09</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.02</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Liverpool</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">−0.14</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.16</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Luton Town</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">0.28</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.03</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Manchester City</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">−0.09</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.2</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Manchester Utd</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">0.04</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.04</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Newcastle Utd</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">−0.19</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.07</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Nott'ham Forest</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">0.01</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.06</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Sheffield Utd</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">0.1</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">−0.03</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Tottenham</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">0.19</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">−0.01</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">West Ham</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">0.18</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.1</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Wolves</td>\n<td headers=\"Opponents' Rating\" class=\"gt_row gt_center\">0.15</td>\n<td headers=\"Opponents' Oppponents Rating\" class=\"gt_row gt_center\">0.05</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" style=\"text-align: left;\" colspan=\"3\">Source: FBref Via {worldfootballR}</td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n### Strength of Schedule\n\nHaving created all the components needed, we must piece it together like a dullard's jigsaw puzzle.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstrength_of_schedule <-\n  remaining_games |>\n  distinct(team) |>\n  left_join(opponent_ratings, by = join_by(team)) |>\n  left_join(opponent_opponent_ratings, by = join_by(team)) |>\n  mutate(\n    unstandardized = (2/3 * opponent_rating) + (1/3 * opponent_opponent_rating),\n    sos = scale(unstandardized)\n  )\n```\n:::\n\n\n\nWe can start by looking at the Premier League title race, comparing Arsenal, Manchester City, and Liverpool's schedules. @tbl-strength-of-schedule shows the results.\n\n\n\n::: {#tbl-strength-of-schedule .cell tbl-cap='Premier League Title Race\\'s Strength of Schedule\n'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Table Code (Click to Expand)\"}\nstrength_of_schedule |>\n  select(team, sos) |> \n  filter(team %in% c(\"Arsenal\", \"Manchester City\", \"Liverpool\")) |> \n  arrange(sos) |> \n  rename(\n    \"Team\" = team,\n    \"Strength of Schedule (Z-Score)\" = sos\n  ) |> \n  gt() |> \n  tab_footnote(\n    footnote = \n      \"z < 0 = Easier than league average; z > 0 = Harder than league average\"\n    ) |> \n  tbl_theme(type = \"num\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yadeaxhmob\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yadeaxhmob table {\n  font-family: Poppins;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yadeaxhmob thead, #yadeaxhmob tbody, #yadeaxhmob tfoot, #yadeaxhmob tr, #yadeaxhmob td, #yadeaxhmob th {\n  border-style: none;\n}\n\n#yadeaxhmob p {\n  margin: 0;\n  padding: 0;\n}\n\n#yadeaxhmob .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yadeaxhmob .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yadeaxhmob .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yadeaxhmob .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yadeaxhmob .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yadeaxhmob .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yadeaxhmob .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yadeaxhmob .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yadeaxhmob .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yadeaxhmob .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yadeaxhmob .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yadeaxhmob .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yadeaxhmob .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yadeaxhmob .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yadeaxhmob .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yadeaxhmob .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yadeaxhmob .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yadeaxhmob .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yadeaxhmob .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yadeaxhmob .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yadeaxhmob .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yadeaxhmob .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yadeaxhmob .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yadeaxhmob .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yadeaxhmob .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yadeaxhmob .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yadeaxhmob .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yadeaxhmob .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yadeaxhmob .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yadeaxhmob .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yadeaxhmob .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yadeaxhmob .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yadeaxhmob .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yadeaxhmob .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yadeaxhmob .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yadeaxhmob .gt_left {\n  text-align: left;\n}\n\n#yadeaxhmob .gt_center {\n  text-align: center;\n}\n\n#yadeaxhmob .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yadeaxhmob .gt_font_normal {\n  font-weight: normal;\n}\n\n#yadeaxhmob .gt_font_bold {\n  font-weight: bold;\n}\n\n#yadeaxhmob .gt_font_italic {\n  font-style: italic;\n}\n\n#yadeaxhmob .gt_super {\n  font-size: 65%;\n}\n\n#yadeaxhmob .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yadeaxhmob .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yadeaxhmob .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yadeaxhmob .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yadeaxhmob .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yadeaxhmob .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yadeaxhmob .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yadeaxhmob .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yadeaxhmob div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Team\">Team</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Strength of Schedule (Z-Score)\">Strength of Schedule (Z-Score)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Liverpool</td>\n<td headers=\"Strength of Schedule (Z-Score)\" class=\"gt_row gt_center\">−1.12</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Manchester City</td>\n<td headers=\"Strength of Schedule (Z-Score)\" class=\"gt_row gt_center\">−0.67</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Arsenal</td>\n<td headers=\"Strength of Schedule (Z-Score)\" class=\"gt_row gt_center\">−0.09</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" style=\"text-align: left;\" colspan=\"2\">Source: FBref Via {worldfootballR}</td>\n    </tr>\n  </tfoot>\n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" style=\"text-align: left;\" colspan=\"2\"> z &lt; 0 = Easier than league average; z &gt; 0 = Harder than league average</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nAs discussed in @sec-sos-methodology, z-scores are a measure of standard deviation from the mean. A z-score of -1.12 means that Liverpool's schedule is 1.12 standard deviations lower than the mean league schedule.\n\nAll three teams' schedules are easier than the league average, which is unsurprising because they have played each other, and many teams still have to play them. However, there is plenty of variance in schedule strength between the three title contenders. Arsenal's schedule is very close to the league average, while Liverpool's remaining schedule is one of the easiest in the Premier League.\n\nFinally, we can plot the Strength of Schedule Z-Scores for all Premier League teams' remaining games this season. The plot below orders teams by SOS, from the hardest schedules to the easiest.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Plot Code (Click to Expand)\"}\nstrength_of_schedule |>\n  mutate(team = forcats::fct_reorder(team, sos)) |>\n  ggplot(aes(x = team, y = sos, fill = sos > 0)) +\n  geom_col(colour = \"grey20\") +\n  geom_hline(yintercept = 0, colour = \"grey20\") +\n  geom_text(\n    aes(\n      label = round(sos, 2),\n      colour = between(sos, -0.25, 0.25),\n      hjust = case_when(\n        between(sos, -0.25, 0) ~ 1.2,\n        between(sos, 0, 0.25) ~ -0.4,\n        sos < -0.25 ~ -0.2,\n        sos > 0.25 ~ 1.2\n        )\n      ),\n    size = 5, fontface = \"bold\", family = \"Poppins\"\n    ) +\n  coord_flip() +\n  scale_fill_manual(values = c(\"#026E99\", \"#D93649\"), guide = \"none\") +\n  scale_colour_manual(values = c(\"white\", \"grey20\"), guide = \"none\") +\n  labs(\n    title = \"Premier League Teams' Strength of Schedule for Remaining Games\",\n    subtitle =\n      stringr::str_wrap(\n        glue::glue(\n          \"Remaining schedule difficulty in the Premier League, represented as \",\n          \"Z-Scores. Scores above zero are harder than league average, below \",\n          \"easier. Z-Scores are the standard deviation distance from the mean \",\n          \"(i.e, scores of +1 (or -1) are 1 SD above (or below) mean).\"\n          ),\n        width = 95\n        ),\n    x = NULL, y = \"Strength of Schedule (Z-Score)\",\n    caption = \"Visualisation: Paul Johnson  |  Data: FBref Via {worldfootballR}\"\n    )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/sos-plot-1.png){fig-alt='A barplot visualising the strength of remaining schedules for every team\nin the Premier League. Positive scores indicate harder than league average\nschedules, and negative scores indicate easier than league average scores.\nThe hardest remaining schedules are Aston Villa (2.42), Luton (1.27), and\nCrystal Palace (0.91), while the easiest schedules are Newcastle (-1.76),\nBrentford (-1.32), and Liverpool (-1.12).\n' width=672}\n:::\n:::\n\n\n\nAston Villa and Luton have much left to play for, so this is not great news for either side. Meanwhile, Newcastle doesn't have to face any of the top three but still have to play Sheffield United and Burnley. Their schedule includes only three teams ranked in the top ten in the baseline team ratings, two of which they will face at St James' Park. Awful slackers.\n\n## Championship Strength of Schedule {#sec-champ}\n\nWe can take another look at this SOS model and how the **fitba** package I've put together works, using the race for automatic promotion in the Championship. As a Southampton fan, I am presenting this as a four-way race that includes Saints, despite their loss to Ipswich on Monday. This choice might seem a little unrealistic. However, I spent four years in a PhD program, so I'm excellent at convincing myself that everything is going great despite the crushing weight of evidence suggesting otherwise.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Data & Model Code (Click to Expand)\"}\nchamp_games <-\n  worldfootballR::fb_match_results(\n    country = \"ENG\", gender = \"M\", season_end_year = 2024, tier = \"2nd\"\n  ) |> \n  fitba::get_fixtures(remaining = TRUE)\n\nchamp_ratings <-\n  worldfootballR::fb_season_team_stats(\n    country = \"ENG\", gender = \"M\", season_end_year = 2024,\n    stat_type = \"standard\", tier = \"2nd\"\n  ) |>\n  fitba::calculate_team_ratings()\n\nchamp_sos <- champ_ratings |> fitba::calculate_sos(schedule = champ_games)\n```\n:::\n\n\n\nThanks to the silly little package I put together, significantly less code is required to put all this together.\n\n@tbl-champ-ratings shows the Championship ratings for the 2023/24 season, highlighting how absurd the top four teams have been^[The same applies to the top three in the Premier League this season. I care less about giving them credit.].\n\n\n\n::: {#tbl-champ-ratings .cell tbl-cap='Baseline Team Ratings in the Championship\n'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Table Code (Click to Expand)\"}\nchamp_ratings |> \n  arrange(desc(rating)) |> \n  janitor::clean_names(case = \"title\") |> \n  rename(\n    \"npxGD/90\" = Npxgd90,\n    \"npGD/90\" = Npgd90\n  ) |> \n  gt() |> \n  tbl_theme(type = \"num\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"uxnawvkmix\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uxnawvkmix table {\n  font-family: Poppins;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uxnawvkmix thead, #uxnawvkmix tbody, #uxnawvkmix tfoot, #uxnawvkmix tr, #uxnawvkmix td, #uxnawvkmix th {\n  border-style: none;\n}\n\n#uxnawvkmix p {\n  margin: 0;\n  padding: 0;\n}\n\n#uxnawvkmix .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uxnawvkmix .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uxnawvkmix .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uxnawvkmix .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uxnawvkmix .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uxnawvkmix .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uxnawvkmix .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uxnawvkmix .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uxnawvkmix .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uxnawvkmix .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uxnawvkmix .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uxnawvkmix .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uxnawvkmix .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uxnawvkmix .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uxnawvkmix .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uxnawvkmix .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uxnawvkmix .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uxnawvkmix .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uxnawvkmix .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uxnawvkmix .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uxnawvkmix .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uxnawvkmix .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uxnawvkmix .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uxnawvkmix .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uxnawvkmix .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uxnawvkmix .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uxnawvkmix .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uxnawvkmix .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uxnawvkmix .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uxnawvkmix .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uxnawvkmix .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uxnawvkmix .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uxnawvkmix .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uxnawvkmix .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uxnawvkmix .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uxnawvkmix .gt_left {\n  text-align: left;\n}\n\n#uxnawvkmix .gt_center {\n  text-align: center;\n}\n\n#uxnawvkmix .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uxnawvkmix .gt_font_normal {\n  font-weight: normal;\n}\n\n#uxnawvkmix .gt_font_bold {\n  font-weight: bold;\n}\n\n#uxnawvkmix .gt_font_italic {\n  font-style: italic;\n}\n\n#uxnawvkmix .gt_super {\n  font-size: 65%;\n}\n\n#uxnawvkmix .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uxnawvkmix .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uxnawvkmix .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uxnawvkmix .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uxnawvkmix .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uxnawvkmix .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uxnawvkmix .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#uxnawvkmix .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#uxnawvkmix div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Team\">Team</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"npxGD/90\">npxGD/90</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"npGD/90\">npGD/90</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Rating\">Rating</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Leeds United</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.82</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.95</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.86</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Leicester City</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.67</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.77</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.7</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Ipswich Town</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.6</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.88</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.68</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Southampton</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.69</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.55</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.65</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">West Brom</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.19</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.52</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.29</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Coventry City</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.24</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.39</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.28</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Middlesbrough</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.3</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.08</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.23</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Watford</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.14</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.18</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.15</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Norwich City</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.02</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.37</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.12</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Sunderland</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.16</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.07</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.09</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Hull City</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">0.03</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.08</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">0.05</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Bristol City</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.09</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">0.03</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.05</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Blackburn</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.01</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.18</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.06</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Stoke City</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.08</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.37</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.17</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Millwall</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.19</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.23</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.2</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Preston</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.3</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.07</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.23</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Swansea City</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.26</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.17</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.23</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">QPR</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.23</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.38</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.28</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Sheffield Weds</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.13</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.63</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.28</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Huddersfield</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.23</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.53</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.32</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Plymouth Argyle</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.41</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.12</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.32</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Birmingham City</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.37</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.45</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.39</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Cardiff City</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−0.55</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−0.35</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−0.49</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Rotherham Utd</td>\n<td headers=\"npxGD/90\" class=\"gt_row gt_center\">−1</td>\n<td headers=\"npGD/90\" class=\"gt_row gt_center\">−1.18</td>\n<td headers=\"Rating\" class=\"gt_row gt_center\">−1.05</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" style=\"text-align: left;\" colspan=\"4\">Source: FBref Via {worldfootballR}</td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nHowever, it is regrettable that my ratings are trying to convince me that Ipswich are good. Sure, they beat Southampton 3-2 on Monday. Still, Southampton were the (slightly) better team, and I watched Cardiff City dominate them earlier in the season, so I am convinced they are frauds that are going to Splendid Vibes their way to the Premier League[^frauds]. Ipswich should be illegal.\n\nHaving calculated the (clearly wrong, disrespectful) team ratings, we can examine the schedules for the four teams left in the race for the automatic promotion spots. @tbl-champ-sos shows the SOS for the Championship's top four teams.\n\n\n\n::: {#tbl-champ-sos .cell tbl-cap='Championship Promotion Race\\'s Strength of Schedule\n'}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Table Code (Click to Expand)\"}\nchamp_sos |>\n  filter(team %in% c(\"Ipswich Town\", \"Leeds United\", \"Leicester City\", \"Southampton\")) |> \n  arrange(sos) |> \n  rename(\n    \"Team\" = team,\n    \"Strength of Schedule (Z-Score)\" = sos\n  ) |> \n  gt() |> \n  tab_footnote(\n    footnote = \n      \"z < 0 = Easier than league average; z > 0 = Harder than league average\"\n    ) |> \n  tbl_theme(type = \"num\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yjotqkofka\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yjotqkofka table {\n  font-family: Poppins;\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yjotqkofka thead, #yjotqkofka tbody, #yjotqkofka tfoot, #yjotqkofka tr, #yjotqkofka td, #yjotqkofka th {\n  border-style: none;\n}\n\n#yjotqkofka p {\n  margin: 0;\n  padding: 0;\n}\n\n#yjotqkofka .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 100%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yjotqkofka .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yjotqkofka .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yjotqkofka .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yjotqkofka .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yjotqkofka .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yjotqkofka .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yjotqkofka .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yjotqkofka .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yjotqkofka .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yjotqkofka .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yjotqkofka .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yjotqkofka .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yjotqkofka .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yjotqkofka .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yjotqkofka .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yjotqkofka .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yjotqkofka .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yjotqkofka .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yjotqkofka .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yjotqkofka .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yjotqkofka .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yjotqkofka .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yjotqkofka .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yjotqkofka .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yjotqkofka .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yjotqkofka .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yjotqkofka .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yjotqkofka .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yjotqkofka .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yjotqkofka .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yjotqkofka .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yjotqkofka .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yjotqkofka .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yjotqkofka .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yjotqkofka .gt_left {\n  text-align: left;\n}\n\n#yjotqkofka .gt_center {\n  text-align: center;\n}\n\n#yjotqkofka .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yjotqkofka .gt_font_normal {\n  font-weight: normal;\n}\n\n#yjotqkofka .gt_font_bold {\n  font-weight: bold;\n}\n\n#yjotqkofka .gt_font_italic {\n  font-style: italic;\n}\n\n#yjotqkofka .gt_super {\n  font-size: 65%;\n}\n\n#yjotqkofka .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yjotqkofka .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yjotqkofka .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yjotqkofka .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yjotqkofka .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yjotqkofka .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yjotqkofka .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yjotqkofka .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yjotqkofka div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Team\">Team</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Strength of Schedule (Z-Score)\">Strength of Schedule (Z-Score)</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Leicester City</td>\n<td headers=\"Strength of Schedule (Z-Score)\" class=\"gt_row gt_center\">−0.28</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Ipswich Town</td>\n<td headers=\"Strength of Schedule (Z-Score)\" class=\"gt_row gt_center\">0.45</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Southampton</td>\n<td headers=\"Strength of Schedule (Z-Score)\" class=\"gt_row gt_center\">1.02</td></tr>\n    <tr><td headers=\"Team\" class=\"gt_row gt_left\">Leeds United</td>\n<td headers=\"Strength of Schedule (Z-Score)\" class=\"gt_row gt_center\">1.1</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" style=\"text-align: left;\" colspan=\"2\">Source: FBref Via {worldfootballR}</td>\n    </tr>\n  </tfoot>\n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" style=\"text-align: left;\" colspan=\"2\"> z &lt; 0 = Easier than league average; z &gt; 0 = Harder than league average</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\nIf the now slim [probability of automatic promotion](https://analytic-fpl.streamlit.app/) wasn't enough, Saints also face one of the most challenging schedules, only beaten by Leeds. Saint have to play Leeds and Leicester before the end of the season, both away from home, in addition to Coventry and Preston, who are still in the hunt for the final playoff spot. Southampton are the toughest team any of the others will face, though Leeds and Ipswich still have to face several playoff chasers, and Leicester are up against multiple relegation candidates. \n\nThings don't look much better when compared to the rest of the league.\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Plot Code (Click to Expand)\"}\nchamp_sos |>\n  mutate(team = forcats::fct_reorder(team, sos)) |>\n  ggplot(aes(x = team, y = sos, fill = sos > 0)) +\n  geom_col(colour = \"grey20\") +\n  geom_hline(yintercept = 0, colour = \"grey20\") +\n  geom_text(\n    aes(\n      label = round(sos, 2),\n      colour = between(sos, -0.25, 0.25),\n      hjust = case_when(\n        between(sos, -0.25, 0) ~ 1.2,\n        between(sos, 0, 0.25) ~ -0.4,\n        sos < -0.25 ~ -0.2,\n        sos > 0.25 ~ 1.2\n        )\n      ),\n    size = 5, fontface = \"bold\", family = \"Poppins\"\n    ) +\n  coord_flip() +\n  scale_fill_manual(values = c(\"#026E99\", \"#D93649\"), guide = \"none\") +\n  scale_colour_manual(values = c(\"white\", \"grey20\"), guide = \"none\") +\n  labs(\n    title = \"Championship Teams' Strength of Schedule for Remaining Games\",\n    subtitle =\n      stringr::str_wrap(\n        glue::glue(\n          \"Remaining schedule difficulty in the Championship, represented as \",\n          \"Z-Scores. Scores above zero are harder than league average, below \",\n          \"easier. Z-Scores are the standard deviation distance from the mean \",\n          \"(i.e, scores of +1 (or -1) are 1 SD above (or below) mean).\"\n          ),\n        width = 95\n        ),\n    x = NULL, y = \"Strength of Schedule (Z-Score)\",\n    caption = \"Visualisation: Paul Johnson  |  Data: FBref Via {worldfootballR}\"\n    )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/championship-sos-plot-1.png){fig-alt='A barplot visualising the strength of remaining schedules for every team\nin the Championship. Positive scores indicate harder than league average\nschedules, and negative scores indicate easier than league average scores.\nThe hardest remaining schedules are Blackburn (1.92), Watford (1.58), and\nCoventry (1.25), while the easiest schedules are Rotherham (-1.61),\nSwansea (-1.46), and Bristol City (-1.33).\n' width=672}\n:::\n:::\n\n\n\nNo problem. Last night I asked ~~my landlord~~ the Championship to increase ~~my rent~~ the gap between the top three and Saints. That's how much I believe in ~~my~~ Southampton's grind/hustle. \n\n[^frauds]:\n    \n    Look, I know this isn't true. For a while, the underlying numbers suggested they might be a \n    level below Leeds, Leicester, and Saints. The numbers haven't had my back for a while now, \n    but I also watched multiple Ipswich games where they never really stood out (though they were \n    pretty good against Southampton on Monday). I know it isn't true. I'm sure I just watched a \n    bad sample of Ipswich games. Let me live.\n\n## Limitations\n\nThe most significant limitation is that this could be a lot more precise. I suspect the team ratings are the area with the greatest room for improvement. The 70%/30% split between npxGD/90 and npGD/90 is acceptable as a starting point, but a more precise approach to measuring team strengths will make a big difference in the final SOS calculations since the ratings do most of the heavy lifting.\n\nThe other major component in the model is how the opponents' opponents are factored in as a means of weighting team ratings more effectively. I like the approach used here. It is a reasonably simple but effective way to get at this issue. That said, I wonder if the weight given to OR and OOR is ideal. I can't think of a more robust approach, but maybe there is a better way to do things? \n\nFinally, from a slightly different angle, should the baseline team ratings incorporate the schedules that each team has faced so that they are a more accurate representation of team strengths^[Yes, they probably should, but I also only just thought of this, and I can't be bothered to go back and fix it right now.]? This doesn't impact the final results of the SOS model, but it would make the team ratings more meaningful.\n\n## Summary\n\nNothing I've done here is particularly fancy or impressive, but SOS seems to be an overlooked area of football analytics, so does this at least fill a small gap? I'm sure SOS hasn't received much attention because it's just not that interesting, and everyone can live without it, but I fancied having a little play around with it, and here we are. \n\nI can't think of a better way to validate these results besides the eye test, but looking over the SOS for both the Premier League and the Championship, the results feel approximately correct. With the [**fitba**](https://paulj1989.github.io/fitba/) package, this approach can be applied to past or remaining schedules. It will be little use if you're trying to measure SOS for the first handful of games in a season, but why would you do that anyway? Stop being a bozo and wait a few games. Regardless, I hope this method can be helpful to someone, even if only inspiring them to come up with something much better because I'm an idiot. \n\n## Acknowledgments {.appendix}\n\nPreview image by [Max Titov](https://unsplash.com/@fearvi) on [Unsplash](https://unsplash.com/photos/black-and-white-board-on-white-metal-frame-wb71RvAuvRY).\n\n## Support {.appendix}\n\nIf you enjoyed this blog post and would like to support my work, you can [buy me a coffee or a beer or give me a tip](https://www.buymeacoffee.com/paulj1989) as a thank you. \n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}